
// Exceptions



//process.on('uncaughtException', function (err) {
    ////throw err;
//});









//try {
    //throw 1111;
//} catch(e) {};




function a() {
    xx
    return "a";
}

function b() {
    setTimeout(function() {
        a();
    });
}

function c() {
    b();
};

c();





